### ISSUE TITLE
Possible Issue in afk.py

### ISSUE THREAD

**Issue by SpEcHiDe** [nitanmarcel/TelegramCompanion-Deprecated#4]
https://github.com/nitanmarcel/TelegramCompanion/blob/d647f782e461fdd9063db5a20960a9b46a38cfc8/tg_companion/modules/afk.py#L41

Hi. I think the if condition **never** evaluates to True.

**Comment by nitanmarcel** [comment]
This issue has been fixed in the V2 release at https://github.com/nitanmarcel/TelegramCompanionV2
